### ISSUE TITLE
sqlalchemy.exc.DataError: (psycopg2.DataError) value too long for type character varying(20)

### ISSUE THREAD

**Issue by Rahel14350** [KerstenDoering/PubMedPortable#11]
Dear Kersten,
I am using this helpful program for text mining of around 600000 papers from Pubmed. Everything worked so far but when I am running: 
python PubMedParser.py -i /home/raheleh/lbi/projects/data_mining/keysearch2/restful_API/data/pancreatic_cancer/ -d pancreatic_cancer_db -p 6
I have this error:
 _Traceback (most recent call last):
  File "PubMedParser.py", line 652, in <module>
    run(options.medline_path, options.clean, int(options.start), options.end, int(options.PROCESSES))
  File "PubMedParser.py", line 615, in run
    res = result.get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
sqlalchemy.exc.DataError: (psycopg2.DataError) value too long for type character varying(20)
 [SQL: 'INSERT INTO pubmed.tbl_comments_correction (fk_pmid, ref_type, ref_source, pmid_version) VALUES (%(fk_pmid)s, %(ref_type)s, %(ref_source)s, %(pmid_version)s) RETURNING pubmed.tbl_comments_correction.id'] [parameters: {'ref_type': 'ExpressionOfConcernIn', 'ref_source': 'BMC Med. 2014 Feb 05;12 :24', 'fk_pmid': 22726540, 'pmid_version': '24499430'}]_

Would you please let me know if you can help me?
Many thanks in advance,
Rahel

**Comment by bgruening** [comment]
Hi @Rahel14350!
It looks like a wrong annotation from pubmed (ref_source': 'BMC Med. 2014 Feb 05;12 :24) is causing the database to error out. This is due to the fact that we allow only 20 characters for this field. You can either increase the limit of 20, or I would fix the matadata from fhe manuscript, it is clearly wrong --- maybe the parser does a mistake here, but I would at first check the XML file.

**Comment by KerstenDoering** [comment]
Hi @Rahel14350,

I increased the column size by one character and additionally included a check for the column size in the parser.

Best,
Kersten
