### ISSUE TITLE
Docker container: PubMedParser.py error with `initial`: value too long for type character varying(10)

### ISSUE THREAD

**Issue by chaxor** [KerstenDoering/PubMedPortable#13]
Thank you for providing the wonderful tool.  I am running the docker container to create the database over all Pubmed and PMC articles. I had to make several small adjustments to the docker container build; although they should be irrelevant to this error (postgres version 9.4 vs 9.1, Debian jessie vs wheezy, 'PubMed2Go' vs 'pubmedportable' naming).

---
**ERROR**:
When creating the database (via `python PubMedParser.py -i /export/import_data/ -d pubmed -p 10`), the input of data stops and throws these errors:

```
Unbekannter Fehler:(raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (psycopg2.DataError) value too long for type character varying(10)
 [SQL: 'INSERT INTO pubmed.tbl_author (fk_pmid, last_name, fore_name, initials, suffix, collective_name) VALUES (%(fk_pmid)s, %(last_name)s, %(fore_name)s, %(initials)s, %(suffix)s, %(collective_name)s) RETURNING pubmed.tbl_author.id'] [parameters: {'last_name': 'Bao', 'collective_name': None, 'fore_name': None, 'suffix': None, 'fk_pmid': 9902741, 'initials': 'Cheng-guang'}]
  warnings.warn("\nUnbekannter Fehler:"+str(e), Warning)
Initialized with  12 processes
Traceback (most recent call last):
  File "PubMedParser.py", line 724, in <module>
    run(options.medline_path, options.clean, int(options.start), options.end, int(options.PROCESSES))
  File "PubMedParser.py", line 687, in run
    res = result.get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
sqlalchemy.exc.DataError: (psycopg2.DataError) value too long for type character varying(10)
 [SQL: 'INSERT INTO pubmed.tbl_author (fk_pmid, last_name, fore_name, initials, suffix, collective_name) VALUES (%(fk_pmid)s, %(last_name)s, %(fore_name)s, %(initials)s, %(suffix)s, %(collective_name)s) RETURNING pubmed.tbl_author.id'] [parameters: {'last_name': 'Bao', 'collective_name': None, 'fore_name': None, 'suffix': None, 'fk_pmid': 9902741, 'initials': 'Cheng-guang'}]
/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py:3779: SAWarning: Textual SQL expression '\n            SELECT \n    ...' should be explicitly declared as text('\n            SELECT \n    ...') (this warning may be suppressed after 10 occurrences)
  {"expr": util.ellipses_string(element)})
```

Another similar error is seen here:

```
Unbekannter Fehler:(raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (psycopg2.DataError) value too long for type character varying(10)
 [SQL: 'INSERT INTO pubmed.tbl_author (fk_pmid, last_name, fore_name, initials, suffix, collective_name) VALUES (%(fk_pmid)s, %(last_name)s, %(fore_name)s, %(initials)s, %(suffix)s, %(collective_name)s) RETURNING pubmed.tbl_author.id'] [parameters: {'last_name': 'Chen', 'collective_name': None, 'fore_name': None, 'suffix': None, 'fk_pmid': 9966621, 'initials': 'Sheng-Zhong'}]
  warnings.warn("\nUnbekannter Fehler:"+str(e), Warning)
/export/import_data/baseline/pubmed18n0471.xml 	pid: 79
Traceback (most recent call last):
  File "PubMedParser.py", line 724, in <module>
    run(options.medline_path, options.clean, int(options.start), options.end, int(options.PROCESSES))
  File "PubMedParser.py", line 687, in run
    res = result.get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
sqlalchemy.exc.DataError: (psycopg2.DataError) value too long for type character varying(10)
 [SQL: 'INSERT INTO pubmed.tbl_author (fk_pmid, last_name, fore_name, initials, suffix, collective_name) VALUES (%(fk_pmid)s, %(last_name)s, %(fore_name)s, %(initials)s, %(suffix)s, %(collective_name)s) RETURNING pubmed.tbl_author.id'] [parameters: {'last_name': 'Chen', 'collective_name': None, 'fore_name': None, 'suffix': None, 'fk_pmid': 9966621, 'initials': 'Sheng-Zhong'}]
```
**POTENTIAL FIX:**
This seems to be a problem with the 'initials' section.

I have not yet been able to test this, as I am still working through learning how to adjust files in docker; however, I have a potential solution.

I believe this can be fixed by altering the lines in PubMedParser.py to contain error handling similar to what is done for `ForeName` - such as this:

```
                        # Forname is restricted to 100 characters
                        if author.find("ForeName") != None and author.find("ForeName").text != None:
                            temp_forname = author.find("ForeName").text
                            if len(temp_forname) < 100:
                                DBAuthor.fore_name = temp_forname
                            else:
                                DBAuthor.fore_name = author.find("ForeName").text[0:97] + "..."

                        if author.find("Initials") != None:
# CHANGED
                            temp_initials = author.find("Initials").text
                            if len(temp_forname) < 100:
                                DBAuthor.initials = temp_initials
                            else:
                                DBAuthor.initials = temp_initials[0:9] + "..."
# CHANGED
```

It may even be usfeul to attemp some type of processing on the error, such as identifying if the field was used for providing several authors (i.e. `Initials` = `"Avishek Saha, Brendan J Gifford, Xiaowei He, Geyou Ao, Ming Zheng, Hiromichi Kataura, Han Htoon, Svetlana Kilina, Sergei Tretiak, Stephen K Doorn"`), such that these can be processed in the correct manner with another loop to split the authors.

- [ ]

**Comment by KerstenDoering** [comment]
Thank you for your detailed bug report. You are right about the solution and the fix is available, now.

There were a few small issues with the Docker build, which are also solved, now (see https://github.com/bgruening/docker-recipes/tree/master/pubmedportable and https://hub.docker.com/r/bgruening/pubmedportable/builds/).

Your Docker adjustments should not be critical for the build, although a renaming of PubMed2Go to PubMedPortable is not really needed. The PubMedPortable wiki (https://github.com/KerstenDoering/PubMedPortable/wiki) shortly explains why there was a renaming.

The Docker build now takes PostgreSQL 9.6, the latest SQLAlchemy version, and Debian Stretch. You might want to make a fresh pull from bgruening/pubmedportable , which automatically takes the latest PubMedPortable version from GitHub (https://github.com/KerstenDoering/PubMedPortable.git).

Regarding you suggestion about splitting the authors, you do not have to split them within the parsing. The XML tag "AuthorList" is processed by the parser, such that every author for a specific PubMed ID can be selected from the database, afterwards. 
Taking the example XML file (in data/pancreatic_cancer_db/), you can check the following SQL command, e.g. in pgAdmin, which will return the list of authors for the PubMed ID 1000475:
SELECT fore_name, last_name, initials FROM pubmed.tbl_author WHERE fk_pmid = 1000475;
For your error message with 'initials': 'Sheng-Zhong', the returned initials string will be "Sheng-Z...".

Feel free to open another issue to provide your thoughts about improving the parser.
